# Generated by Django 3.1.3 on 2021-03-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amievent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, verbose_name='Amievent name')),
                ('date', models.DateField(verbose_name='Amievent date')),
                ('block', models.CharField(max_length=120, verbose_name='block name')),
                ('manager', models.CharField(max_length=120, verbose_name='manager name')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
