# Generated by Django 3.1.3 on 2021-03-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0002_amievent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
