# Generated by Django 3.1.3 on 2021-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0003_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=20, verbose_name='block')),
                ('Fname', models.CharField(max_length=50, verbose_name='Fname')),
                ('Lname', models.CharField(max_length=50, verbose_name='Lname')),
                ('Mnum', models.CharField(max_length=12, verbose_name='Mnum')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
