# Generated by Django 3.1.3 on 2021-04-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0004_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Fname',
            field=models.CharField(max_length=150, verbose_name='Fname'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Lname',
            field=models.CharField(max_length=150, verbose_name='Lname'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Mnum',
            field=models.CharField(max_length=123, verbose_name='Mnum'),
        ),
        migrations.AlterField(
            model_name='register',
            name='block',
            field=models.CharField(max_length=120, verbose_name='block'),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='email'),
        ),
    ]
