# Generated by Django 3.1.3 on 2021-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0005_auto_20210401_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122, verbose_name='first_name')),
                ('last_name', models.DateField(max_length=122, verbose_name='last_name')),
                ('block', models.CharField(max_length=120, verbose_name='block name')),
                ('branch', models.CharField(max_length=120, verbose_name='branch')),
                ('university', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
