# Generated by Django 3.1.3 on 2021-04-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0006_auto_20210408_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=122, verbose_name='last_name')),
                ('email', models.EmailField(max_length=125, verbose_name='email')),
                ('block', models.CharField(max_length=120, verbose_name='block name')),
                ('branch', models.CharField(max_length=120, verbose_name='branch')),
                ('phone_number', models.CharField(max_length=10, verbose_name='phone_number')),
                ('university', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
