# Generated by Django 3.2.4 on 2021-10-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEST', '0007_auto_20210409_0105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amievent',
        ),
    ]
